# Config module
from .config import *
from .db_config import *
from .llm_config import *

__all__ = [
    "PROJECT_ROOT", "DATA_DIR", "LOGS_DIR",
    "ASSISTANT_NAME", "WAKE_WORD", "LANGUAGE", "TIMEZONE",
    "DEBUG", "VERBOSE",
    "AUDIO_SAMPLE_RATE", "AUDIO_CHUNK_SIZE", "AUDIO_DEVICE_INDEX",
    "PROACTIVE_CHECK_INTERVAL", "PROACTIVE_EVENTS_AHEAD_MINUTES",
    "WHISPER_MODEL", "PIPER_MODEL",
    "LOG_LEVEL", "LOG_FILE",
    "MONGO_URI", "DB_NAME",
    "OLLAMA_BASE_URL", "LLM_MODEL", "EMBEDDING_MODEL",
    "TEMPERATURE", "MAX_TOKENS", "TOOL_CALLING_ENABLED",
    "MAX_CONTEXT_MESSAGES"
]
